### ISSUE TITLE
Air 33 required?

### ISSUE THREAD

**Issue by daniel-hopkins** [marpies/air-android-utils#1]
Thank you for updating your android utils.
I tried implementing it today, but I get this error when trying to install on a device.
Is the new Harman Air 33 requred?
I realize 33 is required for 64bit, but I guess I was hoping to use this with Adobe air 32.

`actionscript Documents/Adobe Flash Builder 4.7/.metadata/.plugins/com.adobe.flexbuilder.project.ui/ANEFiles/[APP_NAME]/com.adobe.flexide.multiplatform.android.platform/com.marpies.ane.androidutils.ane [META-INF/ANE/extension.xml]: error 102: Invalid namespace http://ns.adobe.com/air/extension/33.0`

**Comment by marpies** [comment]
Thanks, I will provide a package for AIR 32 and older.

**Comment by daniel-hopkins** [comment]
That sounds great. I look forward to trying them out!

**Comment by marpies** [comment]
The extension should now work with AIR 32 and older.
