### ISSUE TITLE
1120: Access of undefined property AIRAndroidUtils

### ISSUE THREAD

**Issue by Tiusami** [marpies/air-android-utils#2]
I'm getting this error with the following method:

`AIRAndroidUtils.setCutoutMode(CutoutMode.DEFAULT);`

I have both the ANE added in my descriptor file as well as

`import com.marpies.ane.androidutils.data.CutoutMode`

**Comment by marpies** [comment]
Did you also import the main class, i.e.

```
import com.marpies.ane.androidutils.AIRAndroidUtils
```

**Comment by Tiusami** [comment]
> Did you also import the main class, i.e.
> 
> ```
> import com.marpies.ane.androidutils.AIRAndroidUtils
> ```

Thank you for your quick reply. Importing the main class solved the issue. The extension is working fine.
